name: First_WorkFlow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "Hello"

            - name: list_files
              run: ls

            - name: read file
              run: cat README.md

#Few things will fail and we will check what is error, how to fix. 